// =============================================================
//  enrichments.js — AI 生成嘅字卡豐富內容（例句 / 記憶鉤 / 配詞）
//  由 Claude 生成，學生離線讀。老師可自由改／加。
//  key = 英文字（對應 words.js 嘅 en）；有邊個字就顯示邊個。
// =============================================================

const ENRICH = {
  about: { ex: "Tell me about your weekend.", exZh: "講下你嘅週末啦。", mn: "a + bout（一樖嘢）→ 關於", col: ["think about", "worry about"] },
  above: { ex: "The plane flew above the clouds.", exZh: "架飛機喺雲上面飛過。", mn: "a + bove（上）→ 在……之上", col: ["above all"] },
  accept: { ex: "I accept your apology.", exZh: "我接受你嘅道歉。", mn: "ac(向) + cept(取) → 接受", col: ["accept responsibility", "accept the fact"] },
  achieve: { ex: "She achieved her goal.", exZh: "佢達成咗目標。", mn: "a + chieve（似 chief 首要）→ 達到首要目標", col: ["achieve a goal", "achieve success"] },
  across: { ex: "Walk across the street.", exZh: "行過馬路。", mn: "a + cross（交叉）→ 橫過", col: ["come across"] },
  act: { ex: "We must act now.", exZh: "我哋必須即刻行動。", mn: "act 本身就係「做」", col: ["act as", "act on"] },
  action: { ex: "Actions speak louder than words.", exZh: "行動勝過說話。", mn: "act + ion（名詞）→ 行動", col: ["take action"] },
  active: { ex: "She is very active in class.", exZh: "佢上堂好活躍。", mn: "act + ive（形容詞）→ 活躍", col: ["take an active role"] },
  activity: { ex: "Reading is my favourite activity.", exZh: "閱讀係我最鍾意嘅活動。", mn: "active + ity → 活動", col: ["outdoor activity"] },
  add: { ex: "Add some sugar to the tea.", exZh: "落啲糖落茶度。", mn: "a + dd（加多個 d）→ 加", col: ["add to", "add up"] },
  address: { ex: "What's your home address?", exZh: "你屋企地址係咩？", mn: "ad + dress → 地址（亦可解「演講」）", col: ["home address", "email address"] },
  admit: { ex: "He admitted his mistake.", exZh: "佢承認咗自己嘅錯。", mn: "ad(向) + mit(送) → 送入 → 承認", col: ["admit to", "admit a mistake"] },
  adult: { ex: "This film is for adults only.", exZh: "呢套戲淨係畀成年人睇。", mn: "a + dult → 成年人", col: ["young adult"] },
  advantage: { ex: "Speaking English is a big advantage.", exZh: "識講英文係好大優勢。", mn: "advance（向前）+ age → 行先＝優勢", col: ["take advantage of"] },
  adventure: { ex: "Their trip was a great adventure.", exZh: "佢哋嘅旅程係一次大冒險。", mn: "ad + venture（冒險）", col: ["sense of adventure"] },
  advice: { ex: "Can you give me some advice?", exZh: "你可唔可以畀啲建議我？", mn: "ad + vise（睇）→ 指點（名詞；動詞係 advise）", col: ["give advice", "take advice"] },
  afraid: { ex: "Don't be afraid.", exZh: "唔使驚。", mn: "a + fraid（似 fright 驚）→ 驚", col: ["be afraid of"] },
  after: { ex: "I'll call you after dinner.", exZh: "我食完飯之後打俾你。", mn: "after ＝ 之後", col: ["after all", "look after"] },
  again: { ex: "Say it again, please.", exZh: "請講多次。", mn: "a + gain（得到）→ 再得到一次", col: ["again and again", "once again"] },
  against: { ex: "I'm against the plan.", exZh: "我反對呢個計劃。", mn: "a + gainst（向住）→ 反對", col: ["against the law", "play against"] },
  agree: { ex: "I agree with you.", exZh: "我同意你。", mn: "a + gree → 同意（反義：disagree）", col: ["agree with", "agree on"] },
  aim: { ex: "My aim is to pass the exam.", exZh: "我嘅目標係考試及格。", mn: "aim ＝ 瞄準／目標", col: ["aim at", "aim to"] },
  allow: { ex: "My parents allow me to go out.", exZh: "我爸爸媽媽允許我出去。", mn: "al + low → 允許", col: ["allow sb to"] },
  almost: { ex: "It's almost five o'clock.", exZh: "差唔多五點喇。", mn: "all + most → 差不多全部", col: [] },
  alone: { ex: "She lives alone.", exZh: "佢自己一個住。", mn: "al + one（一個）→ 獨自", col: ["leave alone"] },
  already: { ex: "I've already finished.", exZh: "我已經做晒。", mn: "all + ready（全部準備好）→ 已經", col: [] },
  also: { ex: "I also want to go.", exZh: "我都想去。", mn: "al + so → 也", col: [] },
  although: { ex: "Although it rained, we went out.", exZh: "雖然落雨，我哋都出咗去。", mn: "al + though → 雖然", col: [] },
  always: { ex: "She is always late.", exZh: "佢永遠都遲到。", mn: "all + ways（所有路）→ 總是", col: [] },
  among: { ex: "Pick one among these.", exZh: "喺呢啲入面揀一個。", mn: "a + mong（混）→ 喺……之中", col: ["among others"] },
  angry: { ex: "Don't be angry with me.", exZh: "唔好嬲我。", mn: "an + gry（似 growl）→ 嬲", col: ["be angry with"] },
  animal: { ex: "I love animals.", exZh: "我鍾意動物。", mn: "ani + mal → 動物", col: [] },
  answer: { ex: "What's the answer?", exZh: "答案係咩？", mn: "an + swer → 回答（亦可做動詞）", col: ["answer the question", "in answer to"] },
  apart: { ex: "They live apart.", exZh: "佢哋分開住。", mn: "a + part（部分）→ 分開", col: ["apart from", "tell apart"] },
  apply: { ex: "I applied for the job.", exZh: "我申請咗呢份工。", mn: "ap + ply（折）→ 申請", col: ["apply for", "apply to"] },
  approach: { ex: "He approached the door.", exZh: "佢行埋門口。", mn: "ap + proach（近）→ 接近", col: ["a new approach", "approach to"] },
  area: { ex: "This area is very safe.", exZh: "呢區好安全。", mn: "area ＝ 地區／範圍", col: ["local area", "in the area"] },
  argue: { ex: "They argue a lot.", exZh: "佢哋成日嗌交。", mn: "ar + gue → 爭論", col: ["argue with", "argue about"] },
  arrive: { ex: "The train arrived late.", exZh: "架火車遲咗到。", mn: "ar + rive（河岸）→ 到岸 → 到達", col: ["arrive at", "arrive in"] },
  art: { ex: "She studies art.", exZh: "佢讀藝術。", mn: "art ＝ 藝術／技巧", col: ["work of art"] },
  ask: { ex: "May I ask a question?", exZh: "我可唔可以問個問題？", mn: "ask ＝ 問／要求", col: ["ask for", "ask sb to"] },
  attention: { ex: "Pay attention, please.", exZh: "請留心。", mn: "at + tent（帳篷）+ ion → 注意", col: ["pay attention to", "attract attention"] },
  available: { ex: "Are you available tomorrow?", exZh: "你聽日得唔得閒？", mn: "a + vail(值) + able → 用得到", col: ["available for", "become available"] },
  avoid: { ex: "Avoid eating too much sugar.", exZh: "避免食太多糖。", mn: "a + void（空）→ 走開 → 避免", col: ["avoid doing", "avoid the risk"] },
  awake: { ex: "I'm still awake.", exZh: "我仲未瞓。", mn: "a + wake（醒）→ 醒著", col: ["stay awake", "wide awake"] },
  aware: { ex: "Are you aware of the rules?", exZh: "你知唔知道規則？", mn: "a + ware（警覺）→ 意識到", col: ["aware of", "become aware"] },
  balance: { ex: "Keep a balance between work and rest.", exZh: "保持工作同休息嘅平衡。", mn: "bi(兩) + lance → 兩邊平衡", col: ["keep balance", "balance between"] },
  beautiful: { ex: "What a beautiful day!", exZh: "天氣真靚！", mn: "beauty + ful → 靚", col: ["beautiful day"] },
  become: { ex: "She became a doctor.", exZh: "佢做咗醫生。", mn: "be + come → 成為", col: ["become aware", "become famous"] },
  begin: { ex: "Let's begin the lesson.", exZh: "我哋開始上堂啦。", mn: "be + gin → 開始（反義：end）", col: ["begin to do", "to begin with"] },
  believe: { ex: "I believe you.", exZh: "我相信你。", mn: "be + lieve → 相信", col: ["believe in", "believe it or not"] },
  between: { ex: "Just between you and me.", exZh: "得我哋兩個知。", mn: "be + twin(兩) + een → 兩者之間", col: ["between you and me", "in between"] },
  big: { ex: "That's a big problem.", exZh: "嗰個係大問題。", mn: "big ＝ 大", col: ["a big deal"] },
  book: { ex: "I read a book every week.", exZh: "我每個禮拜睇一本書。", mn: "book 亦可做動詞＝預訂（book a ticket）", col: ["book a ticket", "read a book"] },
  bring: { ex: "Bring your umbrella.", exZh: "帶把遮。", mn: "b + ring → 帶嚟（bring → brought）", col: ["bring up", "bring about"] },
  build: { ex: "They built a new house.", exZh: "佢哋起咗間新屋。", mn: "build ＝ 建造（build → built）", col: ["build up", "build a house"] },
  busy: { ex: "I'm busy right now.", exZh: "我而家好忙。", mn: "busy ＝ 忙", col: ["busy with", "get busy"] },
  buy: { ex: "I bought a new phone.", exZh: "我買咗部新電話。", mn: "buy ＝ 買（buy → bought）", col: ["buy sb sth", "buy back"] },
  care: { ex: "Take care of yourself.", exZh: "照顧自己。", mn: "care ＝ 關心／照顧", col: ["take care of", "care about"] },
  carry: { ex: "He carried the heavy bags.", exZh: "佢拎住啲重袋。", mn: "car + ry → 運載", col: ["carry on", "carry out"] },
  chance: { ex: "Give me a chance.", exZh: "畀次機會我。", mn: "chance ＝ 機會", col: ["by chance", "take a chance"] },
  change: { ex: "People can change.", exZh: "人係會變嘅。", mn: "change ＝ 改變／找續", col: ["change your mind", "for a change"] },
  choose: { ex: "Choose your favourite.", exZh: "揀你最鍾意嗰個。", mn: "choose ＝ 選（choose → chose → chosen）", col: ["choose to do", "choose between"] },
  common: { ex: "It's a common mistake.", exZh: "呢個係常見嘅錯。", mn: "com + mon（共同）→ 共有 → 常見", col: ["common sense", "have in common"] },
  complete: { ex: "I completed the form.", exZh: "我填妥咗張表。", mn: "com + plete（滿）→ 完成／完整", col: ["complete a task", "complete with"] },
  consider: { ex: "Consider your options.", exZh: "考慮下你嘅選擇。", mn: "con + sider（星）→ 觀星 → 思考", col: ["consider doing", "consider as"] },
  decide: { ex: "I decided to leave.", exZh: "我決定走。", mn: "de + cide（切）→ 切斷 → 決定", col: ["decide to do", "decide on"] },
  develop: { ex: "We develop new skills.", exZh: "我哋發展新技能。", mn: "de + velop（包）→ 展開 → 發展", col: ["develop into", "develop a habit"] },
};

if (typeof window !== "undefined") window.ENRICH = ENRICH;
