// =============================================================
//  words-senior.js — 高中（DSE）預設字表
//  396 個字，從 2012–2014 DSE Paper 1 閱讀篇章抽取，
//  附例句（ex / exZh）同記憶鉤（mn）。學生離線用到。
//  老師若喺後台「高中 → 字表」貼字，Firestore 會覆蓋呢個預設。
// =============================================================

var WORDS_SENIOR = [
  { en: "archaeologist", pos: ["Noun"], zh: "考古學家", ex: "The archaeologist discovered an ancient tomb.", exZh: "考古學家發現咗一座古墓。", mn: "archaeo（古）+ logist（學者）→ 研究古代嘅學者" },
  { en: "dazzling", pos: ["Adjective"], zh: "耀眼的", ex: "She wore a dazzling diamond necklace.", exZh: "佢戴住一條耀眼嘅鑽石頸鏈。", mn: "dazzle（使目眩）+ ing" },
  { en: "spectacle", pos: ["Noun"], zh: "壯觀的景象", ex: "The fireworks were a magnificent spectacle.", exZh: "煙花係一幕壯觀嘅景象。", mn: "spect（睇）+ acle → 值得睇嘅景象" },
  { en: "emperor", pos: ["Noun"], zh: "皇帝", ex: "The emperor ruled the empire for forty years.", exZh: "皇帝統治帝國四十年。", mn: "empire（帝國）嘅統治者" },
  { en: "tomb", pos: ["Noun"], zh: "墳墓", ex: "They found gold inside the ancient tomb.", exZh: "佢哋喺古墓入面搵到黃金。", mn: "tomb 讀音似『塘』→ 塘邊嘅墳墓" },
  { en: "unearth", pos: ["Verb"], zh: "發掘；出土", ex: "Workers unearthed a statue on the site.", exZh: "工人喺地盤發掘出一座雕像。", mn: "un（出）+ earth（泥）→ 由泥入面掘出嚟" },
  { en: "sculpt", pos: ["Verb"], zh: "雕塑", ex: "He sculpted a horse from clay.", exZh: "佢用泥塑咗一隻馬。", mn: "sculpture（雕塑）嘅動詞" },
  { en: "reassemble", pos: ["Verb"], zh: "重新組裝", ex: "They reassembled the broken vase.", exZh: "佢哋將爛咗嘅花樽重新組裝。", mn: "re（再）+ assemble（組裝）" },
  { en: "sheathe", pos: ["Verb"], zh: "包裹；覆蓋", ex: "The sword was sheathed in leather.", exZh: "把劍用皮革包住。", mn: "sheath（鞘）→ 入鞘；包住" },
  { en: "brilliant", pos: ["Adjective"], zh: "色彩鮮豔的；傑出的", ex: "The sky was brilliant blue.", exZh: "天空係鮮豔嘅藍色。", mn: "brilliant 同 bright 同源 → 光亮、出眾" },
  { en: "hue", pos: ["Noun"], zh: "色彩；色調", ex: "The leaves turned a golden hue.", exZh: "樹葉變成金黃色調。", mn: "hue 讀音似『休』→ 休閒嘅色彩" },
  { en: "monochrome", pos: ["Adjective"], zh: "單色的", ex: "The photo was in monochrome.", exZh: "張相係單色嘅。", mn: "mono（單）+ chrome（色）" },
  { en: "multicoloured", pos: ["Adjective"], zh: "多色的", ex: "The bird has multicoloured feathers.", exZh: "隻雀有多色羽毛。", mn: "multi（多）+ coloured（色）" },
  { en: "grandiose", pos: ["Adjective"], zh: "浮誇的；宏大的", ex: "He had grandiose plans for the city.", exZh: "佢對城市有宏大嘅計劃。", mn: "grand（大）+ iose → 過分宏大" },
  { en: "unify", pos: ["Verb"], zh: "統一", ex: "The king unified the kingdoms.", exZh: "國王統一咗各個王國。", mn: "uni（一）+ fy（化）→ 合成一個" },
  { en: "dynasty", pos: ["Noun"], zh: "朝代", ex: "The Ming dynasty lasted nearly 300 years.", exZh: "明朝延續咗近三百年。", mn: "dyna（力量）→ 一脈相傳嘅統治家族" },
  { en: "reign", pos: ["Noun"], zh: "在位期；統治", ex: "During her reign, trade flourished.", exZh: "喺佢統治期間，貿易興盛。", mn: "reign 讀音似『潤』→ 潤澤一方嘅統治" },
  { en: "tyrannical", pos: ["Adjective"], zh: "暴虐的", ex: "The tyrannical ruler jailed his critics.", exZh: "暴虐嘅統治者監禁批評者。", mn: "tyrant（暴君）嘅形容詞" },
  { en: "standardise", pos: ["Verb"], zh: "標準化", ex: "The government standardised the tests.", exZh: "政府將測驗標準化。", mn: "standard（標準）+ ise" },
  { en: "currency", pos: ["Noun"], zh: "貨幣", ex: "The euro is the currency of many countries.", exZh: "歐元係好多國家嘅貨幣。", mn: "current（流通）→ 流通嘅錢" },
  { en: "afterlife", pos: ["Noun"], zh: "來世", ex: "They believed the king would rule in the afterlife.", exZh: "佢哋相信國王喺來世都會統治。", mn: "after（之後）+ life（人生）→ 死後嘅人生" },
  { en: "somber", pos: ["Adjective"], zh: "陰沉的", ex: "The news put him in a somber mood.", exZh: "呢個消息令佢心情陰沉。", mn: "somber 同 shadow 有關 → 陰暗" },
  { en: "procession", pos: ["Noun"], zh: "行列；隊伍", ex: "A funeral procession moved slowly down the street.", exZh: "送葬隊伍喺街頭緩慢前進。", mn: "process（前進）+ ion → 向前行嘅隊伍" },
  { en: "supernatural", pos: ["Adjective"], zh: "超自然的", ex: "The film is about supernatural forces.", exZh: "套戲講超自然力量。", mn: "super（超）+ natural（自然）" },
  { en: "excavation", pos: ["Noun"], zh: "發掘", ex: "The excavation revealed a Roman villa.", exZh: "發掘揭示咗一座羅馬別墅。", mn: "ex（出）+ cav（洞）→ 掘出個洞" },
  { en: "disintegrate", pos: ["Verb"], zh: "瓦解；粉碎", ex: "The old paper disintegrated in his hands.", exZh: "張舊紙喺佢手中粉碎。", mn: "dis（散）+ integrate（結合）→ 散開" },
  { en: "flake", pos: ["Verb"], zh: "剝落", ex: "The old paint is flaking off.", exZh: "舊油漆剝落緊。", mn: "flake 即一片片剝落" },
  { en: "vibrant", pos: ["Adjective"], zh: "鮮豔的；充滿活力的", ex: "The market was full of vibrant colours.", exZh: "市集充滿鮮豔色彩。", mn: "vibrate（震動）→ 有活力" },
  { en: "serendipity", pos: ["Noun"], zh: "機緣巧合", ex: "Finding the book was pure serendipity.", exZh: "搵到呢本書純屬機緣巧合。", mn: "Serendip（斯里蘭卡舊名）童話嘅意外發現" },
  { en: "preservation", pos: ["Noun"], zh: "保存；保護", ex: "The preservation of old buildings is important.", exZh: "保存舊建築好重要。", mn: "preserve（保存）嘅名詞" },
  { en: "adorn", pos: ["Verb"], zh: "裝飾", ex: "Flowers adorned the entrance.", exZh: "入口用花裝飾。", mn: "ad + orn（裝飾）" },
  { en: "specimen", pos: ["Noun"], zh: "樣本；標本", ex: "The museum has a rare specimen.", exZh: "博物館有一個罕有標本。", mn: "speci（睇）→ 拎嚟睇嘅樣本" },
  { en: "artifact", pos: ["Noun"], zh: "文物；人工製品", ex: "The vase is a precious artifact.", exZh: "個花樽係珍貴文物。", mn: "arti（技藝）+ fact（製品）" },
  { en: "trench", pos: ["Noun"], zh: "溝渠；戰壕", ex: "Soldiers hid in the trench.", exZh: "士兵匿喺戰壕。", mn: "trench 讀音似『填』→ 填掘出嘅溝" },
  { en: "strew", pos: ["Verb"], zh: "散佈", ex: "Toys were strewn across the floor.", exZh: "玩具散佈喺地板。", mn: "strew 即四處散放" },
  { en: "bristle", pos: ["Verb"], zh: "密佈；豎起", ex: "The bushes bristled with thorns.", exZh: "叢林密佈荊棘。", mn: "bristle 本義係鬃毛 → 豎起" },
  { en: "bronze", pos: ["Noun", "Adjective"], zh: "青銅", ex: "The statue is made of bronze.", exZh: "座雕像是青銅造嘅。", mn: "bronze 讀音似『棕』→ 棕紅色金屬" },
  { en: "remnants", pos: ["Noun"], zh: "殘餘；遺跡", ex: "Only remnants of the wall remain.", exZh: "城牆淨低殘餘。", mn: "remain（保留）嘅殘餘" },
  { en: "chariot", pos: ["Noun"], zh: "戰車", ex: "The king rode in a golden chariot.", exZh: "國王坐住金戰車。", mn: "chariot 讀音似『拆』→ 古代戰車" },
  { en: "unveil", pos: ["Verb"], zh: "揭開；揭露", ex: "They unveiled a new statue.", exZh: "佢哋為新雕像揭幕。", mn: "un（去）+ veil（面紗）→ 揭開面紗" },
  { en: "delicate", pos: ["Adjective"], zh: "精緻的；脆弱的", ex: "Handle the delicate glass with care.", exZh: "小心處理易碎嘅玻璃。", mn: "delic（令人愉悅）→ 精細脆弱" },
  { en: "intact", pos: ["Adjective"], zh: "完好無損的", ex: "The vase remained intact after the fall.", exZh: "跌咗之後花樽完好無損。", mn: "in（未）+ tact（碰）→ 未被碰損" },
  { en: "crimson", pos: ["Noun", "Adjective"], zh: "深紅色", ex: "The leaves turned crimson in autumn.", exZh: "樹葉秋天變成深紅色。", mn: "crimson 讀音似『克』→ 濃烈嘅紅" },
  { en: "textile", pos: ["Noun"], zh: "紡織品", ex: "The factory produces fine textiles.", exZh: "工廠生產優質紡織品。", mn: "text（編織）→ 織出嚟嘅布" },
  { en: "distinctive", pos: ["Adjective"], zh: "獨特的", ex: "She has a distinctive voice.", exZh: "佢把聲好獨特。", mn: "distinct（獨特）+ ive" },
  { en: "artistry", pos: ["Noun"], zh: "藝術性；工藝", ex: "The carving shows great artistry.", exZh: "雕刻展現高超工藝。", mn: "artist（藝術家）+ ry" },
  { en: "flourish", pos: ["Verb"], zh: "興盛；繁榮", ex: "The business flourished last year.", exZh: "生意舊年興盛。", mn: "flour（花）→ 開花般繁榮" },
  { en: "palette", pos: ["Noun"], zh: "調色板；色彩", ex: "The artist chose a warm palette.", exZh: "畫家揀咗暖色調。", mn: "palette 即畫家嘅調色板" },
  { en: "infuse", pos: ["Verb"], zh: "注入；滲透", ex: "Her words infused hope into the team.", exZh: "佢嘅話為團隊注入希望。", mn: "in（入）+ fuse（注）→ 注入" },
  { en: "adhere", pos: ["Verb"], zh: "黏附", ex: "The label adhered to the bottle.", exZh: "標籤黐住個樽。", mn: "ad + here（貼近）→ 黐住" },
  { en: "chemist", pos: ["Noun"], zh: "化學家", ex: "The chemist developed a new formula.", exZh: "化學家研發咗新配方。", mn: "chemistry（化學）嘅人" },
  { en: "reapply", pos: ["Verb"], zh: "重新塗上；再次申請", ex: "Reapply sunscreen every two hours.", exZh: "每兩個鐘要再搽防曬。", mn: "re（再）+ apply（塗／申請）" },
  { en: "flank", pos: ["Noun", "Verb"], zh: "側面；位於……側面", ex: "Trees flanked the road.", exZh: "樹木位於馬路兩側。", mn: "flank 即側翼" },
  { en: "mound", pos: ["Noun"], zh: "土堆", ex: "They climbed the grassy mound.", exZh: "佢哋爬上草地土堆。", mn: "mound 即一堆土" },
  { en: "uncover", pos: ["Verb"], zh: "揭露；發掘", ex: "Reporters uncovered the scandal.", exZh: "記者揭露咗醜聞。", mn: "un（去）+ cover（蓋）→ 揭開" },
  { en: "acrobat", pos: ["Noun"], zh: "雜技演員", ex: "The acrobat walked on the tightrope.", exZh: "雜技演員行鋼線。", mn: "acro（高處）+ bat（行）→ 高處行走" },
  { en: "extensive", pos: ["Adjective"], zh: "廣泛的；大規模的", ex: "The fire caused extensive damage.", exZh: "火災造成廣泛破壞。", mn: "ex（外）+ tens（伸）→ 伸展好廣" },
  { en: "amaze", pos: ["Verb"], zh: "使驚嘆", ex: "Her talent amazed everyone.", exZh: "佢嘅才華令所有人驚嘆。", mn: "a + maze（迷惑）→ 令人驚奇" },
  { en: "pigment", pos: ["Noun"], zh: "顏料；色素", ex: "The pigment gives the paint its colour.", exZh: "色素令油漆有顏色。", mn: "pigment 來自拉丁『顏料』" },
  { en: "fissure", pos: ["Noun"], zh: "裂縫", ex: "A fissure appeared in the wall.", exZh: "牆出現裂縫。", mn: "fiss（裂）→ 裂開嘅縫" },
  { en: "fracture", pos: ["Noun", "Verb"], zh: "斷裂；裂縫", ex: "He fractured his arm in the fall.", exZh: "佢跌親整斷咗手臂。", mn: "fract（破）→ 斷裂" },
  { en: "imperfection", pos: ["Noun"], zh: "缺陷", ex: "She saw no imperfection in his work.", exZh: "佢喺佢嘅作品睇唔到瑕疵。", mn: "im（不）+ perfect（完美）" },
  { en: "plaster", pos: ["Verb", "Noun"], zh: "塗灰泥；石膏", ex: "They plastered the wall.", exZh: "佢哋喺牆上塗灰泥。", mn: "plaster 即石膏／灰泥" },
  { en: "modest", pos: ["Adjective"], zh: "謙虛的", ex: "He was modest about his success.", exZh: "佢對自己嘅成就好謙虛。", mn: "mod（適度）→ 不誇張" },
  { en: "handiwork", pos: ["Noun"], zh: "手工製品", ex: "The cake was her handiwork.", exZh: "個蛋糕係佢嘅手作。", mn: "handy（手巧）+ work（作品）" },
  { en: "persimmon", pos: ["Noun"], zh: "柿子", ex: "The persimmon was sweet and soft.", exZh: "個柿又甜又軟。", mn: "persimmon 讀音似『破事』→ 紅橙色嘅果" },
  { en: "jagged", pos: ["Adjective"], zh: "參差不齊的", ex: "The rock had jagged edges.", exZh: "塊石頭邊緣參差。", mn: "jag（缺口）→ 凹凸不平" },
  { en: "callused", pos: ["Adjective"], zh: "長滿老繭的", ex: "His callused hands showed years of work.", exZh: "佢生滿老繭嘅手顯出多年勞動。", mn: "callus（老繭）+ ed" },
  { en: "burial", pos: ["Noun", "Adjective"], zh: "埋葬", ex: "They held a burial at sea.", exZh: "佢哋舉行海葬。", mn: "bury（埋葬）嘅名詞" },
  { en: "mortal", pos: ["Adjective"], zh: "凡人的；致命的", ex: "All humans are mortal.", exZh: "所有人都會死。", mn: "mort（死）→ 會死嘅" },
  { en: "dystopia", pos: ["Noun"], zh: "反烏托邦", ex: "The novel describes a bleak dystopia.", exZh: "本小說描寫一個灰暗嘅反烏托邦。", mn: "dys（壞）+ topia（地方）→ 壞地方（反義 utopia）" },
  { en: "imaginary", pos: ["Adjective"], zh: "想像的；虛構的", ex: "The child had an imaginary friend.", exZh: "個細路有個想像中嘅朋友。", mn: "image（影像）→ 想像出嚟" },
  { en: "authoritarian", pos: ["Adjective"], zh: "獨裁的", ex: "The government grew more authoritarian.", exZh: "政府變得更獨裁。", mn: "authority（權威）→ 過分用權" },
  { en: "oppressive", pos: ["Adjective"], zh: "壓迫的", ex: "The heat was oppressive.", exZh: "酷熱令人透不過氣。", mn: "oppress（壓迫）+ ive" },
  { en: "avert", pos: ["Verb"], zh: "避免；避開", ex: "She averted her eyes from the scene.", exZh: "佢避開咗個場面。", mn: "a（離）+ vert（轉）→ 轉開" },
  { en: "inhabit", pos: ["Verb"], zh: "居住於", ex: "Rare birds inhabit the island.", exZh: "罕有嘅雀鳥住喺島上。", mn: "in（入）+ habit（住）→ 住入" },
  { en: "autonomy", pos: ["Noun"], zh: "自主（權）", ex: "The region was granted autonomy.", exZh: "呢個地區獲授予自治權。", mn: "auto（自己）+ nomy（法）→ 自己管自己" },
  { en: "routinely", pos: ["Adverb"], zh: "例行地", ex: "He routinely checks his email first.", exZh: "佢慣例首先查電郵。", mn: "routine（常規）+ ly" },
  { en: "conducive", pos: ["Adjective"], zh: "有助於……的", ex: "Silence is conducive to study.", exZh: "安靜有助學習。", mn: "con + duce（引導）→ 引導向好" },
  { en: "trilogy", pos: ["Noun"], zh: "三部曲", ex: "The film is the last of a trilogy.", exZh: "套戲係三部曲嘅最後一部。", mn: "tri（三）+ logy → 三部作品" },
  { en: "depict", pos: ["Verb"], zh: "描繪", ex: "The mural depicts village life.", exZh: "壁畫描繪鄉村生活。", mn: "de + pict（畫）→ 畫出嚟" },
  { en: "futuristic", pos: ["Adjective"], zh: "未來派的", ex: "The building has a futuristic design.", exZh: "棟樓有未來感嘅設計。", mn: "future（未來）+ istic" },
  { en: "arena", pos: ["Noun"], zh: "競技場", ex: "The concert was held in a huge arena.", exZh: "音樂會喺大型場館舉行。", mn: "arena 即競技場" },
  { en: "fervently", pos: ["Adverb"], zh: "熱烈地", ex: "She fervently hoped for peace.", exZh: "佢熱切期盼和平。", mn: "ferv（熱）→ 熱烈" },
  { en: "installment", pos: ["Noun"], zh: "（連載的）一集", ex: "The latest installment came out today.", exZh: "最新一集今日出版。", mn: "install（安裝）→ 一段段裝落去" },
  { en: "intricately", pos: ["Adverb"], zh: "複雜地", ex: "The design was intricately carved.", exZh: "圖案雕刻得複雜精細。", mn: "intricate（複雜）+ ly" },
  { en: "conform", pos: ["Verb"], zh: "順從；遵從", ex: "Students must conform to the rules.", exZh: "學生必須遵守規則。", mn: "con（共同）+ form（形）→ 跟住同一個形式" },
  { en: "evolutionary", pos: ["Adjective"], zh: "進化的", ex: "The discovery is an evolutionary step.", exZh: "呢個發現係進化嘅一步。", mn: "evolution（進化）+ ary" },
  { en: "labyrinth", pos: ["Noun"], zh: "迷宮", ex: "The old castle was a labyrinth.", exZh: "古堡好似迷宮。", mn: "labyrinth 即迷宮" },
  { en: "provoke", pos: ["Verb"], zh: "激起；挑釁", ex: "His remarks provoked anger.", exZh: "佢嘅說話激起憤怒。", mn: "pro（前）+ voke（喊）→ 挑起" },
  { en: "agony", pos: ["Noun"], zh: "極大痛苦", ex: "He was in agony after the injury.", exZh: "受傷後佢痛不欲生。", mn: "agon（鬥爭）→ 痛苦掙扎" },
  { en: "imprison", pos: ["Verb"], zh: "監禁", ex: "He was imprisoned for ten years.", exZh: "佢被判監十年。", mn: "im（入）+ prison（監獄）" },
  { en: "infinite", pos: ["Adjective"], zh: "無限的", ex: "The universe seems infinite.", exZh: "宇宙似乎無限。", mn: "in（不）+ finite（有限）" },
  { en: "gigantic", pos: ["Adjective"], zh: "巨大的", ex: "They built a gigantic statue.", exZh: "佢哋建造咗一座巨大雕像。", mn: "giant（巨人）→ 巨大" },
  { en: "overlord", pos: ["Noun"], zh: "霸主", ex: "The overlord demanded total loyalty.", exZh: "霸主要求絕對效忠。", mn: "over（在上）+ lord（主）" },
  { en: "preoccupation", pos: ["Noun"], zh: "盤算；專注的事", ex: "Money was his main preoccupation.", exZh: "錢係佢最掛心嘅事。", mn: "pre（先）+ occupy（佔據）→ 佔據心思" },
  { en: "speculate", pos: ["Verb"], zh: "推測", ex: "Experts speculate about the cause.", exZh: "專家推測原因。", mn: "spec（睇）→ 睇住推測" },
  { en: "aftermath", pos: ["Noun"], zh: "後果；餘波", ex: "In the aftermath of the storm, many lost homes.", exZh: "風暴過後，好多人失去家園。", mn: "after（後）+ math（割）→ 收割後嘅後果" },
  { en: "drawback", pos: ["Noun"], zh: "缺點", ex: "The plan's main drawback is the cost.", exZh: "計劃最大缺點係成本。", mn: "draw（拉）+ back → 拖後腿" },
  { en: "harmonious", pos: ["Adjective"], zh: "和諧的", ex: "They live in a harmonious community.", exZh: "佢哋住喺和諧社區。", mn: "harmony（和諧）+ ous" },
  { en: "consequence", pos: ["Noun"], zh: "後果", ex: "He must face the consequences.", exZh: "佢必須面對後果。", mn: "con + sequ（跟）→ 跟住嚟嘅結果" },
  { en: "exhaustion", pos: ["Noun"], zh: "耗盡", ex: "She collapsed from exhaustion.", exZh: "佢因為力竭而暈倒。", mn: "ex（出）+ haust（抽）→ 抽乾" },
  { en: "narrative", pos: ["Noun"], zh: "敘事", ex: "The film has a powerful narrative.", exZh: "套戲有強烈嘅敘事。", mn: "narrate（講）→ 講述嘅故事" },
  { en: "adolescent", pos: ["Noun", "Adjective"], zh: "青少年", ex: "Many adolescents feel misunderstood.", exZh: "好多青少年覺得唔被人明白。", mn: "adolesce（成長）→ 成長中嘅人" },
  { en: "disaffection", pos: ["Noun"], zh: "不滿", ex: "Disaffection with the government grew.", exZh: "對政府嘅不滿升溫。", mn: "dis（不）+ affection（好感）" },
  { en: "heroine", pos: ["Noun"], zh: "女主角", ex: "The heroine saved the village.", exZh: "女主角拯救咗條村。", mn: "hero + ine（女性）" },
  { en: "enclave", pos: ["Noun"], zh: "飛地；孤立群落", ex: "The town is an enclave of artists.", exZh: "呢個鎮係藝術家嘅聚落。", mn: "en + clave（鎖）→ 鎖入嘅地方" },
  { en: "tranquil", pos: ["Adjective"], zh: "寧靜的", ex: "The lake was tranquil at dawn.", exZh: "黎明時湖面寧靜。", mn: "tran（靜）→ 平靜" },
  { en: "misfit", pos: ["Noun"], zh: "與環境格格不入的人", ex: "He always felt like a misfit.", exZh: "佢總覺得自己格格不入。", mn: "mis（錯）+ fit（合）→ 唔啱" },
  { en: "incongruity", pos: ["Noun"], zh: "不協調", ex: "There was an incongruity in his story.", exZh: "佢個故事有不協調之處。", mn: "in（不）+ congruous（協調）" },
  { en: "facade", pos: ["Noun"], zh: "表面；假象", ex: "Her smile was just a facade.", exZh: "佢嘅笑容只係假象。", mn: "facade（建築正面）→ 表面" },
  { en: "utopia", pos: ["Noun"], zh: "烏托邦", ex: "They dreamed of building a utopia.", exZh: "佢哋夢想建立烏托邦。", mn: "u（無）+ topia（地方）→ 理想中嘅地方" },
  { en: "miserable", pos: ["Adjective"], zh: "悲慘的", ex: "The weather made everyone miserable.", exZh: "天氣令所有人都好慘。", mn: "misery（痛苦）+ able" },
  { en: "contrary", pos: ["Adjective"], zh: "相反的", ex: "The result was contrary to expectations.", exZh: "結果同預期相反。", mn: "contra（反）→ 相反" },
  { en: "unbearable", pos: ["Adjective"], zh: "難以忍受的", ex: "The pain was unbearable.", exZh: "痛到難以忍受。", mn: "un（不）+ bear（忍受）" },
  { en: "terrain", pos: ["Noun"], zh: "地形", ex: "The terrain was rough and rocky.", exZh: "地形崎嶇多石。", mn: "terra（地）→ 土地形勢" },
  { en: "predecessor", pos: ["Noun"], zh: "前任；前輩", ex: "Her predecessor left a mess.", exZh: "佢嘅前任留低個爛攤子。", mn: "pre（先）+ decessor（退者）→ 先退位嘅人" },
  { en: "grim", pos: ["Adjective"], zh: "陰暗的；冷酷的", ex: "The future looked grim.", exZh: "前景黯淡。", mn: "grim 即冷酷無情" },
  { en: "protagonist", pos: ["Noun"], zh: "主角", ex: "The protagonist faces many challenges.", exZh: "主角面對好多挑戰。", mn: "proto（首）+ agonist（角）→ 第一角色" },
  { en: "defeat", pos: ["Noun", "Verb"], zh: "擊敗；失敗", ex: "They defeated the rival team.", exZh: "佢哋擊敗咗對手。", mn: "de + feat（做）→ 做低對手" },
  { en: "crucial", pos: ["Adjective"], zh: "關鍵的", ex: "Sleep is crucial for health.", exZh: "睡眠對健康好關鍵。", mn: "crux（十字關鍵）→ 至關重要" },
  { en: "admonitory", pos: ["Adjective"], zh: "告誡的", ex: "He gave an admonitory glance.", exZh: "佢投以告誡嘅一眼。", mn: "admonish（告誡）+ ory" },
  { en: "extrapolate", pos: ["Verb"], zh: "推斷", ex: "We can extrapolate from these figures.", exZh: "我哋可以從呢啲數字推斷。", mn: "extra（外）+ polate（放）→ 向外推" },
  { en: "deplorable", pos: ["Adjective"], zh: "惡劣的；應受譴責的", ex: "The working conditions were deplorable.", exZh: "工作環境惡劣。", mn: "deplore（強烈反對）+ able" },
  { en: "reluctant", pos: ["Adjective"], zh: "不情願的", ex: "He was reluctant to leave.", exZh: "佢唔太想走。", mn: "re（反）+ luct（掙扎）→ 掙扎不願" },
  { en: "extinction", pos: ["Noun"], zh: "滅絕", ex: "The species faces extinction.", exZh: "呢個物種面臨滅絕。", mn: "ex（出）+ tinct（熄）→ 熄滅" },
  { en: "equivocate", pos: ["Verb"], zh: "模稜兩可；含糊其辭", ex: "The minister equivocated on the issue.", exZh: "部長喺問題上含糊其辭。", mn: "equi（相等）→ 兩邊都咁，唔肯表態" },
  { en: "delusion", pos: ["Noun"], zh: "錯覺；妄想", ex: "He suffers from delusions of grandeur.", exZh: "佢有自大妄想。", mn: "de + lude（玩）→ 被欺騙" },
  { en: "catastrophe", pos: ["Noun"], zh: "災難", ex: "The earthquake was a catastrophe.", exZh: "地震係一場災難。", mn: "cata（下）+ strophe（翻）→ 翻轉崩塌" },
  { en: "apocalypse", pos: ["Noun"], zh: "大災難；末日", ex: "The film shows a nuclear apocalypse.", exZh: "套戲展現核子末日。", mn: "apo（揭）+ calypse → 揭示末日" },
  { en: "imply", pos: ["Verb"], zh: "暗示", ex: "Are you implying I'm wrong?", exZh: "你係咪暗示我錯？", mn: "im（入）+ ply（折）→ 折入暗示" },
  { en: "essentially", pos: ["Adverb"], zh: "本質上", ex: "They are essentially the same.", exZh: "佢哋本質上一樣。", mn: "essence（本質）+ ally" },
  { en: "feckless", pos: ["Adjective"], zh: "不負責任的；無能的", ex: "His feckless son wasted the money.", exZh: "佢個無能嘅仔敗晒啲錢。", mn: "feck（效力）+ less → 冇效用" },
  { en: "hedonism", pos: ["Noun"], zh: "享樂主義", ex: "The city is known for its hedonism.", exZh: "呢個城市以享樂主義聞名。", mn: "hedon（快樂）→ 追求快樂" },
  { en: "scold", pos: ["Verb"], zh: "責罵", ex: "She scolded the children for being late.", exZh: "佢鬧遲到嘅細路。", mn: "scold 即責罵" },
  { en: "sting", pos: ["Noun", "Verb"], zh: "刺痛", ex: "The bee's sting hurt.", exZh: "蜜蜂螫得好痛。", mn: "sting 即刺／螫" },
  { en: "genre", pos: ["Noun"], zh: "體裁；類型", ex: "Horror is my favourite genre.", exZh: "恐怖係我最鍾意嘅類型。", mn: "genre（法文『種類』）" },
  { en: "didactic", pos: ["Adjective"], zh: "說教的", ex: "The story has a didactic tone.", exZh: "個故事有說教意味。", mn: "didact（教導）→ 說教" },
  { en: "counterpart", pos: ["Noun"], zh: "對應的人／物", ex: "She met her counterpart in Japan.", exZh: "佢見咗日本嘅對應官員。", mn: "counter（對）+ part（部分）" },
  { en: "indictment", pos: ["Noun"], zh: "控訴", ex: "The report is an indictment of the system.", exZh: "份報告係對制度嘅控訴。", mn: "in + dict（說）→ 說出指控" },
  { en: "fable", pos: ["Noun"], zh: "寓言", ex: "The fable teaches a lesson.", exZh: "寓言帶出教訓。", mn: "fable 即寓言故事" },
  { en: "outlandish", pos: ["Adjective"], zh: "古怪的；稀奇古怪的", ex: "He wore an outlandish costume.", exZh: "佢著住古怪嘅衫。", mn: "out（外）+ land → 外地奇異" },
  { en: "extravagant", pos: ["Adjective"], zh: "奢華的；過分的", ex: "She threw an extravagant party.", exZh: "佢搞咗個奢華派對。", mn: "extra（外）+ vagant（走）→ 走出常規" },
  { en: "conduit", pos: ["Noun"], zh: "管道；渠道", ex: "Email is a conduit for information.", exZh: "電郵係資訊嘅渠道。", mn: "con + duit（引）→ 引導嘅管道" },
  { en: "disapprove", pos: ["Verb"], zh: "不贊成", ex: "Her parents disapprove of her choice.", exZh: "佢父母唔贊成佢嘅選擇。", mn: "dis（不）+ approve（贊成）" },
  { en: "incite", pos: ["Verb"], zh: "煽動", ex: "He was charged with inciting violence.", exZh: "佢被控煽動暴力。", mn: "in（入）+ cite（喚）→ 喚起" },
  { en: "conceive", pos: ["Verb"], zh: "構想", ex: "She conceived a clever plan.", exZh: "佢構想咗個巧妙計劃。", mn: "con + ceive（取）→ 心中取得" },
  { en: "quaint", pos: ["Adjective"], zh: "古雅的", ex: "We stayed in a quaint inn.", exZh: "我哋住喺間古雅嘅旅館。", mn: "quaint 即古趣" },
  { en: "outdated", pos: ["Adjective"], zh: "過時的", ex: "The software is outdated.", exZh: "軟件已過時。", mn: "out + date（日期）→ 過咗期" },
  { en: "intolerable", pos: ["Adjective"], zh: "無法忍受的", ex: "The noise became intolerable.", exZh: "噪音變得無法忍受。", mn: "in（不）+ toler（忍受）" },
  { en: "apology", pos: ["Noun"], zh: "道歉", ex: "Please accept my apology.", exZh: "請接受我嘅道歉。", mn: "apo（離）+ logy（說）→ 說開誤會" },
  { en: "synthesise", pos: ["Verb"], zh: "合成", ex: "The body synthesises vitamin D.", exZh: "身體會合成維他命D。", mn: "syn（共）+ the（放）→ 放埋一齊" },
  { en: "confirm", pos: ["Verb"], zh: "確認", ex: "Please confirm your booking.", exZh: "請確認你嘅預訂。", mn: "con + firm（堅定）→ 肯定" },
  { en: "identity", pos: ["Noun"], zh: "身份", ex: "He kept his identity secret.", exZh: "佢隱瞞身份。", mn: "ident（相同）→ 證明係同一個" },
  { en: "unfurl", pos: ["Verb"], zh: "展開", ex: "The flag unfurled in the wind.", exZh: "旗幟喺風中展開。", mn: "un（去）+ furl（捲）→ 攤開" },
  { en: "scoundrel", pos: ["Noun"], zh: "無賴", ex: "The scoundrel stole her purse.", exZh: "個無賴偷咗佢個銀包。", mn: "scoundrel 即惡棍" },
  { en: "rumor", pos: ["Noun"], zh: "謠言", ex: "Rumors spread quickly online.", exZh: "謠言喺網上快速傳開。", mn: "rumor 即傳聞" },
  { en: "forgive", pos: ["Verb"], zh: "原諒", ex: "I forgive you.", exZh: "我原諒你。", mn: "for（給予）+ give → 給予寬恕" },
  { en: "sufficient", pos: ["Adjective"], zh: "足夠的", ex: "We have sufficient food.", exZh: "我哋有足夠食物。", mn: "suf（下）+ fic（做）→ 做得夠" },
  { en: "compete", pos: ["Verb"], zh: "競爭", ex: "They compete for the prize.", exZh: "佢哋爭奪獎項。", mn: "com + pete（追求）→ 一齊追求" },
  { en: "squat", pos: ["Adjective"], zh: "矮胖的", ex: "The squat building looked old.", exZh: "矮胖嘅樓睇落好舊。", mn: "squat 即蹲低、矮" },
  { en: "plain-looking", pos: ["Adjective"], zh: "樣貌平凡的", ex: "He was a plain-looking man.", exZh: "佢係個樣貌平凡嘅男人。", mn: "plain（平凡）+ looking" },
  { en: "hotshot", pos: ["Noun"], zh: "能幹好出風頭的人", ex: "The young hotshot rose fast.", exZh: "年輕嘅好手升得好快。", mn: "hot + shot → 紅人" },
  { en: "blink", pos: ["Verb"], zh: "眨（眼）；閃爍", ex: "She blinked in the bright light.", exZh: "佢喺強光下眨眼。", mn: "blink 即一眨" },
  { en: "scratch", pos: ["Verb"], zh: "刮花；刮損", ex: "Don't scratch the screen.", exZh: "唔好刮花個屏幕。", mn: "scratch 即刮" },
  { en: "unplug", pos: ["Verb"], zh: "拔除……的插頭", ex: "Unplug the charger when done.", exZh: "用完拔咗個叉電器。", mn: "un（去）+ plug（插）" },
  { en: "porch", pos: ["Noun"], zh: "門廊", ex: "They sat on the front porch.", exZh: "佢哋坐喺前門廊。", mn: "porch 即門廊" },
  { en: "tablet", pos: ["Noun"], zh: "平板電腦；藥片", ex: "She read on a tablet.", exZh: "佢喺平板度睇嘢。", mn: "tablet 即藥片／平板" },
  { en: "instruction", pos: ["Noun"], zh: "指示；說明", ex: "Read the instructions first.", exZh: "先睇說明。", mn: "in + struct（建）→ 指導" },
  { en: "definitely", pos: ["Adverb"], zh: "肯定地", ex: "I will definitely come.", exZh: "我一定嚟。", mn: "de + finite（定）→ 明確" },
  { en: "celebrity", pos: ["Noun"], zh: "名人", ex: "The hotel is full of celebrities.", exZh: "酒店住滿名人。", mn: "celebrate（慶祝）→ 被人注目" },
  { en: "autobiography", pos: ["Noun"], zh: "自傳", ex: "He wrote his autobiography.", exZh: "佢寫咗自傳。", mn: "auto（自己）+ bio（生命）+ graphy（寫）" },
  { en: "excerpt", pos: ["Noun"], zh: "摘錄", ex: "She read an excerpt from the book.", exZh: "佢讀咗本書嘅一段。", mn: "ex（出）+ cerpt（摘）" },
  { en: "comedian", pos: ["Noun"], zh: "喜劇演員", ex: "The comedian made everyone laugh.", exZh: "喜劇演員令大家都笑。", mn: "comedy（喜劇）嘅人" },
  { en: "gesture", pos: ["Noun"], zh: "手勢", ex: "He made a rude gesture.", exZh: "佢做咗個無禮嘅手勢。", mn: "gesture 即手勢" },
  { en: "disbelief", pos: ["Noun"], zh: "不相信", ex: "She stared in disbelief.", exZh: "佢難以置信咁望住。", mn: "dis（不）+ belief（相信）" },
  { en: "undeserving", pos: ["Adjective"], zh: "不配的", ex: "He is undeserving of praise.", exZh: "佢唔配得到讚賞。", mn: "un（不）+ deserve（值得）" },
  { en: "autograph", pos: ["Noun"], zh: "親筆簽名", ex: "She asked for his autograph.", exZh: "佢要咗佢嘅簽名。", mn: "auto（自己）+ graph（寫）" },
  { en: "anonymous", pos: ["Adjective"], zh: "匿名的", ex: "The donation was anonymous.", exZh: "捐款係匿名嘅。", mn: "an（無）+ nym（名）→ 冇名" },
  { en: "supremacy", pos: ["Noun"], zh: "至高無上", ex: "They fought for naval supremacy.", exZh: "佢哋爭奪海上霸權。", mn: "supreme（最高）+ acy" },
  { en: "shallow", pos: ["Adjective"], zh: "膚淺的", ex: "His arguments were shallow.", exZh: "佢嘅論點膚淺。", mn: "shallow 即淺" },
  { en: "entangle", pos: ["Verb"], zh: "纏住", ex: "The wires got entangled.", exZh: "電線纏埋一齊。", mn: "en + tangle（糾纏）" },
  { en: "venerate", pos: ["Verb"], zh: "尊敬；崇拜", ex: "They venerate their ancestors.", exZh: "佢哋敬重祖先。", mn: "vener（敬）→ 尊敬" },
  { en: "sustenance", pos: ["Noun"], zh: "營養；支持", ex: "Bread was their main sustenance.", exZh: "麵包係佢哋主要食糧。", mn: "sustain（維持）→ 維生之物" },
  { en: "discernible", pos: ["Adjective"], zh: "可辨別的", ex: "There was no discernible change.", exZh: "睇唔到明顯變化。", mn: "discern（辨別）+ ible" },
  { en: "phenomenon", pos: ["Noun"], zh: "現象", ex: "Auroras are a natural phenomenon.", exZh: "極光係自然現象。", mn: "phen（顯現）→ 顯現嘅事" },
  { en: "propensity", pos: ["Noun"], zh: "傾向", ex: "He has a propensity for risk.", exZh: "佢有冒險傾向。", mn: "pro + pens（掛）→ 掛住某事" },
  { en: "worship", pos: ["Verb"], zh: "崇拜", ex: "They worship at the temple.", exZh: "佢哋喺廟崇拜。", mn: "worth（價值）+ ship → 視為有價值" },
  { en: "idol", pos: ["Noun"], zh: "偶像", ex: "She is a teen idol.", exZh: "佢係青少年偶像。", mn: "idol 即偶像" },
  { en: "adoration", pos: ["Noun"], zh: "崇拜；愛慕", ex: "Fans gazed in adoration.", exZh: "粉絲愛慕咁望住。", mn: "adore（愛慕）+ ation" },
  { en: "daft", pos: ["Adjective"], zh: "傻的；愚蠢的", ex: "That was a daft idea.", exZh: "嗰個係傻嘅念頭。", mn: "daft 即傻" },
  { en: "veneration", pos: ["Noun"], zh: "尊崇", ex: "The relics are held in veneration.", exZh: "聖物受人尊崇。", mn: "venerate 嘅名詞" },
  { en: "militant", pos: ["Adjective"], zh: "激進的；好戰的", ex: "Militant protesters clashed with police.", exZh: "激進示威者同警察衝突。", mn: "milit（兵）→ 好戰" },
  { en: "intellectual", pos: ["Adjective"], zh: "智力的", ex: "The debate was intellectual.", exZh: "辯論係智力層面嘅。", mn: "intellect（智力）+ ual" },
  { en: "spiritual", pos: ["Adjective"], zh: "精神的", ex: "Music meets a spiritual need.", exZh: "音樂滿足精神需要。", mn: "spirit（精神）+ ual" },
  { en: "moral", pos: ["Adjective"], zh: "道德的", ex: "He has high moral standards.", exZh: "佢道德標準好高。", mn: "mor（風俗）→ 道德" },
  { en: "fame", pos: ["Noun"], zh: "名聲", ex: "She rose to fame overnight.", exZh: "佢一夜成名。", mn: "fame 即名聲" },
  { en: "delusional", pos: ["Adjective"], zh: "妄想的", ex: "He is delusional about his skills.", exZh: "佢對自己能力有妄想。", mn: "delusion + al" },
  { en: "snare", pos: ["Noun"], zh: "陷阱", ex: "The fox was caught in a snare.", exZh: "狐狸中咗陷阱。", mn: "snare 即陷阱" },
  { en: "proportion", pos: ["Noun"], zh: "比例", ex: "A large proportion agreed.", exZh: "大部分同意。", mn: "pro + portion（部分）" },
  { en: "universal", pos: ["Adjective"], zh: "普遍的", ex: "Music is a universal language.", exZh: "音樂係通用語言。", mn: "uni（一）+ vers（轉）→ 全體" },
  { en: "talentless", pos: ["Adjective"], zh: "無才華的", ex: "The critic called the show talentless.", exZh: "影評話個騷毫無才華。", mn: "talent + less" },
  { en: "patron", pos: ["Noun"], zh: "顧客；常客", ex: "Patrons enjoy free Wi-Fi.", exZh: "顧客可享免費Wi-Fi。", mn: "pater（父）→ 像父般照顧嘅人" },
  { en: "terminal", pos: ["Noun"], zh: "終端機；候機樓", ex: "We met at the airport terminal.", exZh: "我哋喺客運大樓會合。", mn: "term（盡頭）→ 盡頭處" },
  { en: "virtual", pos: ["Adjective"], zh: "虛擬的", ex: "They had a virtual meeting.", exZh: "佢哋開咗個網上會議。", mn: "virtue（效能）→ 唔係實體但有作用" },
  { en: "refreshment", pos: ["Noun"], zh: "茶點；小食", ex: "Refreshments will be served.", exZh: "將會供應茶點。", mn: "re + fresh（新鮮）→ 提神食物" },
  { en: "pastime", pos: ["Noun"], zh: "消遣", ex: "Reading is my favourite pastime.", exZh: "閱讀係我至愛嘅消遣。", mn: "pass（打發）+ time（時間）" },
  { en: "admission", pos: ["Noun"], zh: "入場費；承認", ex: "Admission is free.", exZh: "免費入場。", mn: "ad + mit（送）→ 准許進入" },
  { en: "import", pos: ["Verb", "Noun"], zh: "進口", ex: "We import oil from abroad.", exZh: "我哋從外地進口石油。", mn: "im（入）+ port（港）" },
  { en: "pioneer", pos: ["Noun"], zh: "先驅；先鋒", ex: "She is a pioneer in the field.", exZh: "佢係呢個領域嘅先驅。", mn: "pioneer 即開拓者" },
  { en: "prestigious", pos: ["Adjective"], zh: "有聲望的", ex: "He won a prestigious award.", exZh: "佢攞咗個聲望高嘅獎。", mn: "prestige（聲望）+ ious" },
  { en: "dreary", pos: ["Adjective"], zh: "沉悶的", ex: "It was a dreary afternoon.", exZh: "嗰個下午好沉悶。", mn: "dreary 即沉悶" },
  { en: "strategic", pos: ["Adjective"], zh: "策略性的", ex: "The bridge is of strategic value.", exZh: "條橋有戰略價值。", mn: "strategy（策略）+ ic" },
  { en: "token", pos: ["Noun"], zh: "代幣；標記", ex: "Insert a token to play.", exZh: "放入代幣玩。", mn: "token 即標記" },
  { en: "immerse", pos: ["Verb"], zh: "沉浸", ex: "She immersed herself in work.", exZh: "佢投入工作。", mn: "im（入）+ merse（浸）" },
  { en: "illustrate", pos: ["Verb"], zh: "插圖；說明", ex: "Let me illustrate with an example.", exZh: "我舉個例說明。", mn: "il + lustr（光）→ 照明" },
  { en: "wit", pos: ["Noun"], zh: "機智", ex: "His wit made everyone laugh.", exZh: "佢嘅機智令大家都笑。", mn: "wit 即機智" },
  { en: "logic", pos: ["Noun"], zh: "邏輯", ex: "Her argument lacks logic.", exZh: "佢嘅論點欠邏輯。", mn: "log（理）→ 推理" },
  { en: "intriguing", pos: ["Adjective"], zh: "引人入勝的", ex: "The plot is intriguing.", exZh: "情節引人入勝。", mn: "intrigue + ing" },
  { en: "console", pos: ["Noun", "Verb"], zh: "遊戲機；安慰", ex: "She consoled her crying friend.", exZh: "佢安慰喊緊嘅朋友。", mn: "con + sole（一起）→ 一起慰藉" },
  { en: "appeal", pos: ["Noun", "Verb"], zh: "吸引力；呼籲", ex: "The design has wide appeal.", exZh: "設計好有吸引力。", mn: "ap + pel（推）→ 推向" },
  { en: "socialise", pos: ["Verb"], zh: "社交", ex: "Children learn to socialise.", exZh: "細路學社交。", mn: "social + ise" },
  { en: "trump", pos: ["Verb"], zh: "勝過", ex: "Safety trumps convenience.", exZh: "安全勝過方便。", mn: "trump 即壓過" },
  { en: "abstract", pos: ["Adjective"], zh: "抽象的", ex: "Beauty is an abstract concept.", exZh: "美係抽象概念。", mn: "abs（離）+ tract（拉）→ 抽離" },
  { en: "interactive", pos: ["Adjective"], zh: "互動的", ex: "The exhibit is interactive.", exZh: "展品係互動嘅。", mn: "inter（互相）+ act" },
  { en: "relief", pos: ["Noun"], zh: "解脫；寬慰", ex: "She sighed with relief.", exZh: "佢鬆一口氣。", mn: "re + lief（輕）→ 輕鬆" },
  { en: "cosy", pos: ["Adjective"], zh: "舒適的", ex: "The room felt cosy.", exZh: "間房好舒適。", mn: "cosy 即溫馨" },
  { en: "initiative", pos: ["Noun"], zh: "倡議；主動", ex: "She took the initiative.", exZh: "佢採取主動。", mn: "initiate（開始）+ ive" },
  { en: "stewardship", pos: ["Noun"], zh: "管理職責", ex: "Good stewardship protects nature.", exZh: "良好管理保護自然。", mn: "steward（管家）+ ship" },
  { en: "recycle", pos: ["Verb"], zh: "回收；循環再用", ex: "We recycle plastic bottles.", exZh: "我哋回收膠樽。", mn: "re + cycle（循環）" },
  { en: "pledge", pos: ["Noun", "Verb"], zh: "承諾；保證", ex: "He pledged to help.", exZh: "佢承諾幫手。", mn: "pledge 即誓言" },
  { en: "volunteer", pos: ["Noun", "Verb"], zh: "義工；自願", ex: "She volunteers at the hospital.", exZh: "佢喺醫院做義工。", mn: "volunt（自願）" },
  { en: "quilt", pos: ["Noun"], zh: "被子", ex: "Grandma made a patchwork quilt.", exZh: "嫲嫲整咗床碎布被。", mn: "quilt 即棉被" },
  { en: "mingle", pos: ["Verb"], zh: "交際；混雜", ex: "Guests mingled at the party.", exZh: "賓客喺派對交際。", mn: "mingle 即混在一起" },
  { en: "embroidery", pos: ["Noun"], zh: "刺繡", ex: "The dress has fine embroidery.", exZh: "條裙有精細刺繡。", mn: "em + broider（繡）" },
  { en: "involvement", pos: ["Noun"], zh: "參與", ex: "Thank you for your involvement.", exZh: "多謝你參與。", mn: "involve + ment" },
  { en: "intrigue", pos: ["Verb"], zh: "引起……的興趣", ex: "The mystery intrigued her.", exZh: "謎團引起佢興趣。", mn: "in + trigue（糾纏）" },
  { en: "conservation", pos: ["Noun"], zh: "保育；保護", ex: "Conservation saves wildlife.", exZh: "保育拯救野生動物。", mn: "con + serve（保存）" },
  { en: "embellish", pos: ["Verb"], zh: "裝飾；潤飾", ex: "She embellished the story.", exZh: "佢潤飾咗個故事。", mn: "em + bell（美）" },
  { en: "decorative", pos: ["Adjective"], zh: "裝飾性的", ex: "The vase is purely decorative.", exZh: "花樽純作裝飾。", mn: "decorate + ive" },
  { en: "bedspread", pos: ["Noun"], zh: "床罩", ex: "She folded the bedspread.", exZh: "佢摺好床罩。", mn: "bed + spread（鋪）" },
  { en: "spokeswoman", pos: ["Noun"], zh: "女發言人", ex: "The spokeswoman issued a statement.", exZh: "女發言人發表聲明。", mn: "spokes（說）+ woman" },
  { en: "organise", pos: ["Verb"], zh: "組織", ex: "Let's organise a trip.", exZh: "我哋組織個 trip。", mn: "organ（器官）→ 組織" },
  { en: "donate", pos: ["Verb"], zh: "捐贈", ex: "They donated to the charity.", exZh: "佢哋捐畀慈善機構。", mn: "don（給）" },
  { en: "leftover", pos: ["Noun"], zh: "剩餘物（多指食物）", ex: "We ate the leftovers.", exZh: "我哋食咗剩菜。", mn: "left + over → 剩低" },
  { en: "reflect", pos: ["Verb"], zh: "反映", ex: "The mirror reflects light.", exZh: "鏡反射光。", mn: "re + flect（彎）→ 反照" },
  { en: "personality", pos: ["Noun"], zh: "性格；個性", ex: "She has a warm personality.", exZh: "佢性格溫暖。", mn: "person + ality" },
  { en: "empower", pos: ["Verb"], zh: "賦權；使自主", ex: "Education empowers people.", exZh: "教育令人自主。", mn: "em + power（力量）" },
  { en: "ultimate", pos: ["Adjective"], zh: "最終的", ex: "Our ultimate goal is peace.", exZh: "我最終目標係和平。", mn: "ultim（最後）" },
  { en: "engage", pos: ["Verb"], zh: "參與；吸引", ex: "The game engages children.", exZh: "遊戲吸引細路。", mn: "en + gage（誓約）→ 投入" },
  { en: "endangered", pos: ["Adjective"], zh: "瀕危的", ex: "Pandas are endangered.", exZh: "熊貓瀕危。", mn: "en + danger + ed" },
  { en: "display", pos: ["Verb", "Noun"], zh: "展覽；陳列", ex: "The shop displays new goods.", exZh: "店舖陳列新貨。", mn: "dis + play（展開）" },
  { en: "provocative", pos: ["Adjective"], zh: "挑釁的；引發爭議的", ex: "The article was provocative.", exZh: "嗰篇文章好具挑釁性。", mn: "pro（向前）+ voc（喊）→ 挑起" },
  { en: "headline", pos: ["Noun"], zh: "標題", ex: "The headline caught my eye.", exZh: "標題吸引咗我。", mn: "head（頭）+ line（行）→ 頂部一行" },
  { en: "spark", pos: ["Verb", "Noun"], zh: "引發；火花", ex: "One spark can start a fire.", exZh: "一粒火花可以引起火警。", mn: "spark 即火花" },
  { en: "memoir", pos: ["Noun"], zh: "回憶錄", ex: "She wrote a memoir of her youth.", exZh: "佢寫咗本青年回憶錄。", mn: "mem（記憶）+ oir" },
  { en: "contrast", pos: ["Noun", "Verb"], zh: "對比；對照", ex: "The contrast is striking.", exZh: "對比好強烈。", mn: "contra（反）+ st（站）→ 對立而立" },
  { en: "firestorm", pos: ["Noun"], zh: "風暴；強烈反響", ex: "The post caused a firestorm.", exZh: "帖文引起強烈反響。", mn: "fire + storm" },
  { en: "intent", pos: ["Noun"], zh: "意圖", ex: "His intent was clear.", exZh: "佢嘅意圖好明顯。", mn: "in + tent（伸）→ 心之所向" },
  { en: "relentless", pos: ["Adjective"], zh: "不懈的；持續的", ex: "The rain was relentless.", exZh: "雨落個不停。", mn: "re + lent（鬆）→ 不鬆懈" },
  { en: "insistence", pos: ["Noun"], zh: "堅持", ex: "Her insistence paid off.", exZh: "佢嘅堅持有回報。", mn: "insist + ence" },
  { en: "mandatory", pos: ["Adjective"], zh: "強制的；必須的", ex: "Attendance is mandatory.", exZh: "必須出席。", mn: "mandate（命令）+ ory" },
  { en: "stun", pos: ["Verb"], zh: "使震驚", ex: "The news stunned everyone.", exZh: "消息震驚所有人。", mn: "stun 即震驚" },
  { en: "shame", pos: ["Noun", "Verb"], zh: "羞恥；使羞愧", ex: "She felt deep shame.", exZh: "佢深感羞恥。", mn: "shame 即羞恥" },
  { en: "insult", pos: ["Noun", "Verb"], zh: "侮辱", ex: "Don't insult me.", exZh: "唔好侮辱我。", mn: "in + sult（跳）→ 跳起攻擊" },
  { en: "envy", pos: ["Noun", "Verb"], zh: "嫉妒；羨慕", ex: "She envied his success.", exZh: "佢嫉妒佢嘅成功。", mn: "envy 即嫉妒" },
  { en: "poise", pos: ["Noun"], zh: "鎮定；優雅", ex: "She handled it with poise.", exZh: "佢從容應對。", mn: "poise 即平衡、從容" },
  { en: "accomplishment", pos: ["Noun"], zh: "成就", ex: "Her accomplishment impressed us.", exZh: "佢嘅成就令我哋印象深刻。", mn: "accomplish + ment" },
  { en: "ironically", pos: ["Adverb"], zh: "諷刺地", ex: "Ironically, he failed the test.", exZh: "諷刺嘅係佢肥咗個測驗。", mn: "irony + ally" },
  { en: "cautionary", pos: ["Adjective"], zh: "勸戒的", ex: "It's a cautionary tale.", exZh: "呢係個警世故事。", mn: "caution（小心）+ ary" },
  { en: "backlash", pos: ["Noun"], zh: "強烈反對；反彈", ex: "The policy caused a backlash.", exZh: "政策引起強烈反對。", mn: "back + lash（鞭）→ 反過來鞭打" },
  { en: "controversy", pos: ["Noun"], zh: "爭議", ex: "The decision sparked controversy.", exZh: "決定引起爭議。", mn: "contra（反）+ versy" },
  { en: "superior", pos: ["Adjective"], zh: "優越的", ex: "Her skills are superior.", exZh: "佢嘅技能優越。", mn: "super（上）→ 在上" },
  { en: "debate", pos: ["Noun", "Verb"], zh: "辯論", ex: "They debated for hours.", exZh: "佢哋辯論咗幾個鐘。", mn: "de + bate（打）→ 交鋒" },
  { en: "upbringing", pos: ["Noun"], zh: "養育；教養", ex: "He had a strict upbringing.", exZh: "佢家教好嚴。", mn: "up + bring + ing" },
  { en: "extracurricular", pos: ["Adjective"], zh: "課外的", ex: "She joins extracurricular activities.", exZh: "佢參加課外活動。", mn: "extra + curriculum" },
  { en: "equivalent", pos: ["Noun", "Adjective"], zh: "對等物；相等的", ex: "One dollar is equivalent to eight yen.", exZh: "一蚊等於八日圓。", mn: "equi（等）+ val（值）" },
  { en: "precisely", pos: ["Adverb"], zh: "確切地", ex: "That's precisely my point.", exZh: "嗰個正正係我嘅觀點。", mn: "precise + ly" },
  { en: "startling", pos: ["Adjective"], zh: "令人吃驚的", ex: "The result was startling.", exZh: "結果令人吃驚。", mn: "start（驚跳）+ ling" },
  { en: "clincher", pos: ["Noun"], zh: "決定性因素", ex: "Price was the clincher.", exZh: "價錢係決定因素。", mn: "clinch（確定）+ er" },
  { en: "convince", pos: ["Verb"], zh: "使確信；說服", ex: "He convinced me to go.", exZh: "佢說服我去。", mn: "con + vince（勝）→ 勝過其疑" },
  { en: "bilingual", pos: ["Adjective"], zh: "雙語的", ex: "She is bilingual in English and Chinese.", exZh: "佢中英雙語。", mn: "bi（兩）+ lingua（語）" },
  { en: "comparatively", pos: ["Adverb"], zh: "比較地", ex: "It's comparatively cheap.", exZh: "佢比較平。", mn: "comparative + ly" },
  { en: "adopt", pos: ["Verb"], zh: "採納；收養", ex: "They adopted a new policy.", exZh: "佢哋採納新政策。", mn: "ad + opt（選）" },
  { en: "guideline", pos: ["Noun"], zh: "指引；方針", ex: "Follow these guidelines.", exZh: "跟住呢啲指引。", mn: "guide + line" },
  { en: "endless", pos: ["Adjective"], zh: "無盡的", ex: "The work seemed endless.", exZh: "工作似無止境。", mn: "end + less" },
  { en: "conduct", pos: ["Verb"], zh: "進行；實施", ex: "They conducted a survey.", exZh: "佢哋進行調查。", mn: "con + duct（引）→ 引導" },
  { en: "majority", pos: ["Noun"], zh: "多數", ex: "The majority agreed.", exZh: "大多數同意。", mn: "major（大）+ ity" },
  { en: "netizen", pos: ["Noun"], zh: "網民", ex: "Netizens reacted angrily.", exZh: "網民憤怒回應。", mn: "net + citizen" },
  { en: "publicise", pos: ["Verb"], zh: "宣傳", ex: "They publicised the event.", exZh: "佢哋宣傳個活動。", mn: "public + ise" },
  { en: "outperform", pos: ["Verb"], zh: "勝過；表現優於", ex: "She outperformed her rivals.", exZh: "佢表現勝過對手。", mn: "out + perform" },
  { en: "contender", pos: ["Noun"], zh: "競爭者", ex: "She is a strong contender.", exZh: "佢係強勁競爭者。", mn: "contend + er" },
  { en: "ethnic", pos: ["Adjective"], zh: "種族的", ex: "The city has many ethnic groups.", exZh: "城市有多個族群。", mn: "ethn（族群）+ ic" },
  { en: "Confucian", pos: ["Adjective"], zh: "儒家的", ex: "Confucian values stress family.", exZh: "儒家價值重視家庭。", mn: "Confucius（孔子）" },
  { en: "declare", pos: ["Verb"], zh: "宣佈", ex: "He declared his intention.", exZh: "佢宣佈意圖。", mn: "de + clare（清楚）→ 講清楚" },
  { en: "thrive", pos: ["Verb"], zh: "蓬勃發展", ex: "The business is thriving.", exZh: "生意蓬勃。", mn: "thrive 即興旺" },
  { en: "priority", pos: ["Noun"], zh: "優先（事）", ex: "Safety is the top priority.", exZh: "安全係首要。", mn: "prior（先）+ ity" },
  { en: "aggregate", pos: ["Noun", "Adjective"], zh: "總數；合計的", ex: "The aggregate score was high.", exZh: "總分好高。", mn: "ag + greg（群）→ 聚成群" },
  { en: "dynamic", pos: ["Adjective"], zh: "充滿活力的；動態的", ex: "She is a dynamic leader.", exZh: "佢係充滿活力嘅領袖。", mn: "dynam（力量）+ ic" },
  { en: "economy", pos: ["Noun"], zh: "經濟", ex: "The economy is growing.", exZh: "經濟增長緊。", mn: "eco（家）+ nomy（管理）" },
  { en: "creativity", pos: ["Noun"], zh: "創造力", ex: "Creativity is valued here.", exZh: "呢度重視創意。", mn: "create + ivity" },
  { en: "population", pos: ["Noun"], zh: "人口", ex: "The population is ageing.", exZh: "人口老化。", mn: "populus（人民）+ ation" },
  { en: "glut", pos: ["Noun"], zh: "供過於求", ex: "A glut of goods lowered prices.", exZh: "貨品過剩令價格下跌。", mn: "glut 即充斥" },
  { en: "appropriate", pos: ["Adjective"], zh: "合適的", ex: "Wear appropriate clothes.", exZh: "著合適嘅衫。", mn: "ap + propri（適當）" },
  { en: "shortage", pos: ["Noun"], zh: "短缺", ex: "There's a water shortage.", exZh: "出現水荒。", mn: "short + age" },
  { en: "comprise", pos: ["Verb"], zh: "由……組成", ex: "The team comprises ten people.", exZh: "隊伍由十人組成。", mn: "com + prise（抓）→ 抓埋一齊" },
  { en: "expectation", pos: ["Noun"], zh: "期望", ex: "He met our expectations.", exZh: "佢達到我哋期望。", mn: "expect + ation" },
  { en: "practical", pos: ["Adjective"], zh: "實用的", ex: "The book gives practical advice.", exZh: "本書提供實用建議。", mn: "practice + al" },
  { en: "multinational", pos: ["Noun", "Adjective"], zh: "跨國的（公司）", ex: "The firm is a multinational.", exZh: "公司係跨國企業。", mn: "multi + national" },
  { en: "privately", pos: ["Adverb"], zh: "私下地", ex: "He complained privately.", exZh: "佢私下抱怨。", mn: "private + ly" },
  { en: "complain", pos: ["Verb"], zh: "投訴；抱怨", ex: "She complained about the food.", exZh: "佢投訴啲食物。", mn: "com + plain（悲嘆）" },
  { en: "clueless", pos: ["Adjective"], zh: "一竅不通的", ex: "He's clueless about computers.", exZh: "佢對電腦一竅不通。", mn: "clue + less" },
  { en: "expat", pos: ["Noun"], zh: "外籍人士", ex: "Many expats live here.", exZh: "好多外籍人士住喺度。", mn: "ex + patriate（離鄉）" },
  { en: "flummox", pos: ["Verb"], zh: "使困惑", ex: "The question flummoxed him.", exZh: "問題令佢困惑。", mn: "flummox 即搞到一頭霧水" },
  { en: "manufacturer", pos: ["Noun"], zh: "製造商", ex: "The manufacturer recalled the cars.", exZh: "製造商回收架車。", mn: "manufacture + er" },
  { en: "hapless", pos: ["Adjective"], zh: "倒霉的", ex: "The hapless victim lost everything.", exZh: "倒霉嘅受害者一無所有。", mn: "hap（運氣）+ less" },
  { en: "tellingly", pos: ["Adverb"], zh: "顯然地", ex: "Tellingly, she said nothing.", exZh: "顯然地佢冇出聲。", mn: "tell + ingly" },
  { en: "decrease", pos: ["Noun", "Verb"], zh: "減少", ex: "Sales decreased last month.", exZh: "上月銷量減少。", mn: "de + crease（少）" },
  { en: "nationwide", pos: ["Adjective", "Adverb"], zh: "全國性的", ex: "The strike was nationwide.", exZh: "罷工係全國性嘅。", mn: "nation + wide" },
  { en: "rite", pos: ["Noun"], zh: "儀式", ex: "Graduation is a rite of passage.", exZh: "畢業係成長儀式。", mn: "rite 即儀式" },
  { en: "freshman", pos: ["Noun"], zh: "（大學）新生", ex: "He's a freshman at university.", exZh: "佢係大學新生。", mn: "fresh + man" },
  { en: "vocational", pos: ["Adjective"], zh: "職業的", ex: "He attends a vocational school.", exZh: "佢讀緊職業學校。", mn: "vocation（職業）+ al" },
  { en: "swirl", pos: ["Verb"], zh: "環繞；流傳", ex: "Rumors swirl around the star.", exZh: "謠言喺明星身邊流傳。", mn: "swirl 即打轉" },
  { en: "adequately", pos: ["Adverb"], zh: "充分地", ex: "The job is adequately paid.", exZh: "份工薪金充足。", mn: "adequate + ly" },
  { en: "expression", pos: ["Noun"], zh: "表達", ex: "Freedom of expression matters.", exZh: "表達自由好重要。", mn: "express + ion" },
  { en: "innovation", pos: ["Noun"], zh: "創新", ex: "Innovation drives progress.", exZh: "創新推動進步。", mn: "innovate + ion" },
  { en: "independently", pos: ["Adverb"], zh: "獨立地", ex: "She works independently.", exZh: "佢獨立工作。", mn: "independent + ly" },
  { en: "ossified", pos: ["Adjective"], zh: "僵化的", ex: "The system has ossified.", exZh: "制度已僵化。", mn: "oss（骨）→ 骨化般僵硬" },
  { en: "resistant", pos: ["Adjective"], zh: "抵抗的", ex: "They are resistant to change.", exZh: "佢哋抗拒改變。", mn: "resist + ant" },
  { en: "stifle", pos: ["Verb"], zh: "壓制；扼殺", ex: "Rules stifle creativity.", exZh: "規則扼殺創意。", mn: "stifle 即焗住" },
  { en: "repressive", pos: ["Adjective"], zh: "壓制性的", ex: "The regime is repressive.", exZh: "政權高壓。", mn: "repress + ive" },
  { en: "lament", pos: ["Verb", "Noun"], zh: "哀嘆", ex: "He lamented the lost time.", exZh: "佢哀嘆浪費咗時間。", mn: "lament 即悲嘆" },
  { en: "cutting-edge", pos: ["Adjective"], zh: "尖端的；前沿的", ex: "They use cutting-edge technology.", exZh: "佢哋用尖端科技。", mn: "cutting（切）+ edge（邊）→ 最前緣" },
  { en: "institution", pos: ["Noun"], zh: "機構；制度", ex: "The school is a respected institution.", exZh: "學校係受尊崇嘅機構。", mn: "institut（設立）+ ion" },
  { en: "administrator", pos: ["Noun"], zh: "行政人員", ex: "The administrator handled the case.", exZh: "行政人員處理個案。", mn: "administer + ator" },
  { en: "woo", pos: ["Verb"], zh: "爭取；追求", ex: "The party woos young voters.", exZh: "黨爭取年輕選民。", mn: "woo 即追求" },
  { en: "relocate", pos: ["Verb"], zh: "重新安置；搬遷", ex: "The firm relocated to Tokyo.", exZh: "公司搬咗去東京。", mn: "re + locate（定位）" },
  { en: "rewarding", pos: ["Adjective"], zh: "有回報的；令人滿足的", ex: "Teaching is rewarding.", exZh: "教書有滿足感。", mn: "reward + ing" },
  { en: "clout", pos: ["Noun"], zh: "影響力", ex: "He has a lot of clout.", exZh: "佢好有影響力。", mn: "clout 即影響力" },
  { en: "hybrid", pos: ["Noun", "Adjective"], zh: "混合物", ex: "The car is a petrol-electric hybrid.", exZh: "架車係油電混合。", mn: "hybrid 即混合" },
  { en: "life-size", pos: ["Adjective"], zh: "真實大小的", ex: "The statue is life-size.", exZh: "雕像係真人大小。", mn: "life + size" },
  { en: "celebrated", pos: ["Adjective"], zh: "著名的", ex: "He is a celebrated artist.", exZh: "佢係著名藝術家。", mn: "celebrate → 受人頌讚" },
  { en: "reconstruct", pos: ["Verb"], zh: "重建", ex: "They reconstructed the event.", exZh: "佢哋重建事件經過。", mn: "re + construct（建造）" },
  { en: "realm", pos: ["Noun"], zh: "領域", ex: "Science is not his realm.", exZh: "科學唔係佢嘅領域。", mn: "realm 即領域" },
  { en: "crucible", pos: ["Noun"], zh: "嚴酷考驗；熔爐", ex: "War is a crucible for leaders.", exZh: "戰爭係領袖嘅考驗。", mn: "cruc（交叉）→ 熔煉" },
  { en: "exposure", pos: ["Noun"], zh: "暴露；接觸", ex: "Sun exposure harms skin.", exZh: "曬太陽傷皮膚。", mn: "ex + pose（放）→ 放出" },
  { en: "lacquer", pos: ["Noun"], zh: "漆", ex: "The table has a lacquer finish.", exZh: "張檯有漆面。", mn: "lacquer 即漆" },
  { en: "preservative", pos: ["Noun"], zh: "防腐劑", ex: "The food has no preservatives.", exZh: "食物無防腐劑。", mn: "preserve + ative" },
  { en: "agent", pos: ["Noun"], zh: "劑；代理人", ex: "She's our agent in Hong Kong.", exZh: "佢係我哋喺香港嘅代理。", mn: "ag（行動）→ 行事者" },
  { en: "acceptable", pos: ["Adjective"], zh: "可接受的", ex: "The offer is acceptable.", exZh: "出價可以接受。", mn: "accept + able" },
  { en: "vast", pos: ["Adjective"], zh: "廣大的", ex: "The desert is vast.", exZh: "沙漠好廣大。", mn: "vast 即廣大" },
  { en: "pace", pos: ["Noun"], zh: "步伐；速度", ex: "The pace of life is fast.", exZh: "生活節奏快。", mn: "pace 即步伐" },
  { en: "quicken", pos: ["Verb"], zh: "加快", ex: "Her pace quickened.", exZh: "佢加快腳步。", mn: "quick + en" },
  { en: "exploratory", pos: ["Adjective"], zh: "試探性的", ex: "They made exploratory calls.", exZh: "佢哋作試探性聯絡。", mn: "explore + atory" },
  { en: "mind-boggling", pos: ["Adjective"], zh: "令人難以置信的", ex: "The cost is mind-boggling.", exZh: "成本令人難以置信。", mn: "mind + boggle（驚退）" },
  { en: "predict", pos: ["Verb"], zh: "預測", ex: "Experts predict growth.", exZh: "專家預測增長。", mn: "pre + dict（說）→ 預先說" },
  { en: "evolution", pos: ["Noun"], zh: "演變；進化", ex: "The evolution of technology is rapid.", exZh: "科技演變好快。", mn: "e + volv（滾）→ 滾向前" },
  { en: "accuracy", pos: ["Noun"], zh: "準確（度）", ex: "Check the accuracy of the data.", exZh: "核對數據準確度。", mn: "accurate + cy" },
  { en: "plainly", pos: ["Adverb"], zh: "明顯地", ex: "He was plainly tired.", exZh: "佢明顯好攰。", mn: "plain + ly" },
  { en: "footloose", pos: ["Adjective"], zh: "自由自在的", ex: "Young and footloose, she travelled.", exZh: "年輕自由嘅佢去旅行。", mn: "foot + loose（鬆）" },
  { en: "cliffhanger", pos: ["Noun"], zh: "吊人胃口的結局", ex: "The episode ends on a cliffhanger.", exZh: "嗰集以懸念結束。", mn: "cliff（崖）+ hang → 吊喺崖邊" },
  { en: "protestation", pos: ["Noun"], zh: "抗議；聲明", ex: "Despite his protestations, they fined him.", exZh: "儘管佢抗議，佢哋都罰佢。", mn: "protest + ation" },
  { en: "anxiety", pos: ["Noun"], zh: "焦慮", ex: "She felt anxiety before the exam.", exZh: "考試前佢焦慮。", mn: "angh（悶）→ 焦急" },
  { en: "nuclear", pos: ["Adjective"], zh: "核子的", ex: "Nuclear power is debated.", exZh: "核能備受爭議。", mn: "nucleus（核）" },
  { en: "assign", pos: ["Verb"], zh: "分配；指派", ex: "The teacher assigned homework.", exZh: "老師派功課。", mn: "as + sign（標）→ 標示分派" },
  { en: "blandly", pos: ["Adverb"], zh: "平淡地", ex: "He smiled blandly.", exZh: "佢淡淡一笑。", mn: "bland（淡）+ ly" },
  { en: "passion", pos: ["Noun"], zh: "熱情", ex: "She has a passion for music.", exZh: "佢對音樂好有熱誠。", mn: "passi（受苦）→ 強烈情感" },
  { en: "frankly", pos: ["Adverb"], zh: "坦白地", ex: "Frankly, I don't care.", exZh: "坦白講我唔在乎。", mn: "frank（坦白）+ ly" },
  { en: "alternative", pos: ["Noun", "Adjective"], zh: "選擇；另類的", ex: "Is there an alternative?", exZh: "有冇其他選擇？", mn: "alter（另一）+ native" },
  { en: "unchecked", pos: ["Adjective"], zh: "未受抑制的", ex: "The fire spread unchecked.", exZh: "火勢不受控制咁蔓延。", mn: "un + check（制止）" },
  { en: "stalk", pos: ["Verb"], zh: "怒沖沖地走", ex: "He stalked out of the room.", exZh: "佢怒氣沖沖咁行出去。", mn: "stalk 即大步走" },
  { en: "chime", pos: ["Verb"], zh: "發出叮聲", ex: "The clock chimed midnight.", exZh: "時鐘敲響午夜。", mn: "chime 即叮聲" },
  { en: "air", pos: ["Verb"], zh: "廣播；播出", ex: "The show airs at eight.", exZh: "節目八點播。", mn: "air（播送）" },
  { en: "approach", pos: ["Verb", "Noun"], zh: "接近；方法", ex: "We need a new approach.", exZh: "我哋需要新方法。", mn: "ap + proach（近）" },
  { en: "compensatory", pos: ["Adjective"], zh: "補償性的", ex: "He received compensatory pay.", exZh: "佢獲得補償薪金。", mn: "compensate + ory" },
  { en: "trail", pos: ["Verb"], zh: "跟隨；拖沓", ex: "The dog trailed behind.", exZh: "狗跟喺後面。", mn: "trail 即拖行" },
  { en: "achievement", pos: ["Noun"], zh: "成就", ex: "Winning the prize is a great achievement.", exZh: "獲獎係大成就。", mn: "achieve + ment" },
  { en: "desire", pos: ["Noun", "Verb"], zh: "渴望；欲望", ex: "He desires success.", exZh: "佢渴望成功。", mn: "de + sire（星）→ 仰望星求" },
  { en: "descent", pos: ["Noun"], zh: "血統；下山", ex: "He is of Chinese descent.", exZh: "佢係華裔。", mn: "de + scent（爬）→ 向下" },
  { en: "eye-opening", pos: ["Adjective"], zh: "令人大開眼界的", ex: "The trip was eye-opening.", exZh: "趟旅程令人大開眼界。", mn: "eye + open" },
  { en: "blue-collar", pos: ["Adjective"], zh: "藍領的", ex: "He does blue-collar work.", exZh: "佢做藍領工作。", mn: "blue（藍衫）+ collar" },
  { en: "white-collar", pos: ["Adjective"], zh: "白領的", ex: "She has a white-collar job.", exZh: "佢做白領工作。", mn: "white（白衫）+ collar" },
  { en: "underclass", pos: ["Noun"], zh: "下層階級", ex: "They form a new underclass.", exZh: "佢哋形成新下層階級。", mn: "under + class" },
  { en: "churn", pos: ["Verb"], zh: "大量生產", ex: "The factory churns out toys.", exZh: "工廠大量生產玩具。", mn: "churn 即攪動" },
  { en: "knob", pos: ["Noun"], zh: "旋鈕", ex: "Turn the knob to open.", exZh: "扭個旋鈕打開。", mn: "knob 即圓把手" },
  { en: "lever", pos: ["Noun"], zh: "槓桿", ex: "Pull the lever down.", exZh: "拉低支槓桿。", mn: "lev（舉）→ 舉起嘅桿" },
  { en: "application", pos: ["Noun"], zh: "申請；應用", ex: "Submit your application online.", exZh: "網上遞交申請。", mn: "apply + ation" },
  { en: "individual", pos: ["Adjective", "Noun"], zh: "個人的；個人", ex: "Each individual is unique.", exZh: "每個人獨一無二。", mn: "in + divid（分）→ 不可再分" },
  { en: "rote", pos: ["Noun"], zh: "死記硬背", ex: "He learns by rote.", exZh: "佢死記硬背。", mn: "rote 即機械重複" },
  { en: "stress", pos: ["Verb", "Noun"], zh: "強調；壓力", ex: "She stressed the importance.", exZh: "佢強調重要性。", mn: "stress 即壓力／強調" },
  { en: "encourage", pos: ["Verb"], zh: "鼓勵", ex: "Teachers encourage students.", exZh: "老師鼓勵學生。", mn: "en + courage（勇氣）" },
  { en: "compulsory", pos: ["Adjective"], zh: "強制的；必修的", ex: "English is compulsory.", exZh: "英文係必修。", mn: "compel + ory" },
  { en: "candidate", pos: ["Noun"], zh: "考生；候選人", ex: "She is the best candidate.", exZh: "佢係最佳人選。", mn: "candid（白）→ 穿白衣嘅求職者" },
  { en: "supplementary", pos: ["Adjective"], zh: "補充的", ex: "Supplementary notes are provided.", exZh: "提供補充筆記。", mn: "supplement + ary" },
  { en: "attain", pos: ["Verb"], zh: "達到", ex: "He attained his goal.", exZh: "佢達成目標。", mn: "at + tain（觸）→ 觸及" },
  { en: "lair", pos: ["Noun"], zh: "巢穴", ex: "The tiger lay in its lair.", exZh: "老虎匿喺巢穴。", mn: "lair 即野獸窩" },
];
if (typeof window !== "undefined") window.WORDS_SENIOR = WORDS_SENIOR;
